GET http://localhost:3000/movies/
###

POST http://localhost:3000/movies/
Content-Type: application/json
###

GET http://localhost:3000/movies/12/
###

PUT http://localhost:3000/movies/24/
###

DELETE http://localhost:3000/movies/5/
###

GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/1/movies/



